# name: Deploy
#
# on:
#   push:
#     branches:
#       - main # Set a branch to deploy when pushed
#
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       # No changes
#
#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#       - name: Build and push
#         uses: docker/build-push-action@v5
#         with:
#           push: true
#           tags: fiqrimasngot/test-build:latest

name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
    tags:
      - "v*" # Trigger the workflow on new tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag or set default
        id: version
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
            echo "VERSION=${{ github.run_number }}-${COMMIT_SHA}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/test-build:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/test-build:${{ env.VERSION }}

      - name: Post build cleanup
        run: docker system prune -f
